### ISSUE TITLE
Archway use cases

### ISSUE THREAD

**Issue by Xe** [Xe/olin#52]
Olin is going to be a hard sell on people. We aren't sure if this works for the use cases we want to try this with. Therefore, I propose we try to prioritize Archway for a small subset of use cases initially:

- fan-out notifications across multiple systems (telegram, discord, apple push notifications, etc)
- "thing happened" incident response
- low-volume chatbot response

**Comment by Mec-iS** [comment]
Do you want to use clients or some other pattern? The handlers will call a client instance or you want them to work with message passing? 
I mean, what is the basic approach/protocol/pattern? It will be good to start from an established pattern among the ones listed [here](http://mytrile.github.io/blog/2010/09/20/zeromq-messaging-patterns/) (ZeroMQ is a good reference for anything distributed).

**Comment by bb010g** [comment]
The [Scalability Protocols](https://staysail.github.io/nng_presentation/nng_presentation.html) and [nng](https://github.com/nanomsg/nng)/[mangos](https://github.com/nanomsg/mangos) are also probably worth looking at.

**Comment by gedw99** [comment]
@Xe Its an easy sell for me. WASM event sourcing is a huge game changer for projects i work on. 
I guess its all about if you only in the could or not.  I am write apps that have to run everywhere & users need to be able to write business logic on top. WASM is the perfect place for them to put them business logic. HTML with little HTTP calls into the Archway Message que to have work processed and to get data back out as evets is aweomly easy for users to write their HTML front ends with.
I have been thinking about stuff like this for a while.

Regarding Archway the message queue, i had a look at the branch.
I like the event store being in boltdb as that runs anywhere.  I worry that there is a lot of edge cases to get right. Still, if we can put Raft or others under the BoltDB that will get some HA. Mangos looks nice.
Also if i have a stupid simple App in HTML and want to interoperate with the system, then the Message queue needs to publish over websockets ? Or do you imagine only the "Microservices / Functions will use this system ?
I was thinking about how you can make a html page and use the simple message handler and events to interact with the system. 

Looking forward to hearing your thoughts.

**Comment by Xe** [comment]
@gedw99 Thank you so much for looking through things and leaving your thoughts. These are incredibly useful to help feel out the design of this into a usable real thing. The implementation in the archway branch is effectively a sketch to feel out the design, none of the tech stack elements it uses are permanent. It uses boltdb for event storage because I am more familiar with convenience tooling to ORM around it. The ultimate event storage for the multi-node cluster setup is going to be probably using either postgres or some other more exciting system as needs demand it. 

With regards to websocket support: what would that look like to you in an ideal world? I was thinking about having events being submitted via a HTTP post, but websocket submission sounds like a useful addition.

**Comment by gedw99** [comment]
The transport must be bi-directional and asynchronous.

Client posts a message that is a mutation event.
Client disconnects.
Server calls client back.

This is the future exchange pattern imho.


This is the paradigm to handle.

I would use a libp2p to get agnostic. This make it easy for future proofing.
It has QUIC.
Webrtc and ortc is almost ready too.
DTLS is ready.

That's enough for a future proofed stack.

**Comment by Xe** [comment]
Moved to Wasmcloud.
