### ISSUE TITLE
Support the CommonWA specification

### ISSUE THREAD

**Issue by losfair** [Xe/olin#7]
Hello, maintainer of [life](https://github.com/perlin-network/life) & author of [CommonWA](https://github.com/CommonWA/cwa-spec) and a few other WebAssembly-based projects here :)

The idea behind Dagger seems to be similar with that of CommonWA, both wanting to provide an OS-level abstraction over the underlying runtime environment for WebAssembly. Do you think it would be better if we work together on CommonWA and try to spread the support over all kinds of systems/runtimes, so that we'll have a unique standard of the WebAssembly runtime environment, and languages that compile to WASM will have a unified target with a full "OS" environment?

**Comment by Xe** [comment]
Yes, I am willing to work with the CommonWA specification, but there has been little movement on actual real-world tasks for it. All of the things described in CommonWA would be easy to implement using this existing environment.

**Comment by Xe** [comment]
I have implemented this in #8, but without a way to test it, verifying this is hard.

**Comment by gedw99** [comment]
If you find a c or java implementation maybe it helps ?

Do they have a wasm binary that they use to test against ?

**Comment by Xe** [comment]
Because the upstream CommonWA specification has no tests, I have [written my own](https://github.com/Xe/olin/blob/cwa/cmd/cwa/testdata/test.rs). I have everything passing but the resource tests because those haven't been written yet.
